logging:
    file:
        name: movie-service.log
    level:
        com:
            jsn:
                booking:
                    app:
                        movie: DEBUG
        org:
            hibernate:
                SQL: DEBUG
            springframework:
                jdbc:
                    datasource:
                        init: DEBUG
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
        root: INFO
server:
    port: 8081
spring:
    application:
        name: movie-service
    datasource:
        password: admin
        url: jdbc:mysql://localhost:3306/b_movieservice?characterEncoding=UTF-8
        username: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
